### PR TITLE
Use TemplateHaskellQuotes rather than TemplateHaskell extension

### PR DESCRIPTION
**Pull request by mpickering**
TemplateHaskell can't be used in boot libraries as not all platforms support evaluating Template Haskell splices. Therefore we should use TemplateHaskellQuotes to be more precise about the requirements which a module places on the host system.

### CODE REVIEW

**Comment by hasufell** [comment]
It seems this change breaks on GHC < 9.0 due to missing Lift instance.

**Comment by mpickering** [comment]
Are you able to investigate and finish this PR @hasufell ?

**Comment by hasufell** [comment]
@mpickering can you review the additional commit?

**Comment by mpickering** [comment]
Looks good to me! Thanks Julian.

**Comment by hasufell** [comment]
https://hackage.haskell.org/package/os-string-2.0.4

**Comment by mpickering** [comment]
Can you please push a tag for the 2.0.4 release?

**Comment by hasufell** [comment]
https://github.com/haskell/os-string/releases/tag/v2.0.4

**Pull request merged**
